name: PSAS Blog
description: Portland State Aerospace Society Blog
url: http://blog.psas.pdx.edu

exclude:    ['README.markdown', 'LICENSE', 'Makefile', 'assets/less', 'assets/lib/bootstrap']
timezone:   America/Los_Angeles
markdown:   kramdown
permalink:  /:year/:month/:title/
excerpt_separator: "\n\n\n\n"

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
