name: PSAS Blog
description: Portland State Aerospace Society is a student aerospace engineering project at Portland State University. We're building ultra-low-cost, open source rockets.
url: http://blog.psas.pdx.edu

exclude:    ['README.markdown', 'LICENSE', 'CNAME', 'Makefile', 'assets/less', 'assets/lib/bootstrap']
timezone:   America/Los_Angeles
markdown:   kramdown
permalink:  /:year/:month/:title/
excerpt_separator: "\n\n\n\n"

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
